name: Build

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@latest

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - run: pnpm install
            - run: pnpm build
